[2023-09-05T09:41:15.062+0000] {processor.py:157} INFO - Started process (PID=240) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:15.064+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:41:15.065+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:15.065+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:15.103+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:15.818+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:15.818+0000] {manager.py:501} INFO - Created Permission View: can delete on DAG:my_first_dag
[2023-09-05T09:41:15.844+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:15.843+0000] {manager.py:501} INFO - Created Permission View: can edit on DAG:my_first_dag
[2023-09-05T09:41:15.862+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:15.861+0000] {manager.py:501} INFO - Created Permission View: can read on DAG:my_first_dag
[2023-09-05T09:41:15.895+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:15.894+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:41:15.922+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:15.921+0000] {dag.py:2929} INFO - Creating ORM DAG for my_first_dag
[2023-09-05T09:41:15.952+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:15.952+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:41:15.997+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.940 seconds
[2023-09-05T09:41:19.144+0000] {processor.py:157} INFO - Started process (PID=245) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:19.146+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:41:19.147+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:19.147+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:19.154+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:19.151+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 9
    ) as dag:
    ^
SyntaxError: invalid syntax
[2023-09-05T09:41:19.155+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:19.194+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.058 seconds
[2023-09-05T09:41:21.168+0000] {processor.py:157} INFO - Started process (PID=250) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:21.169+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:41:21.171+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:21.170+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:21.176+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:21.174+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 8
    schedule
    ^
SyntaxError: positional argument follows keyword argument
[2023-09-05T09:41:21.177+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:21.237+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.080 seconds
[2023-09-05T09:41:23.291+0000] {processor.py:157} INFO - Started process (PID=255) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:23.300+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:41:23.302+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:23.301+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:23.314+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:23.313+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 8
    schedule_in
    ^
SyntaxError: positional argument follows keyword argument
[2023-09-05T09:41:23.319+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:23.381+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.104 seconds
[2023-09-05T09:41:24.347+0000] {processor.py:157} INFO - Started process (PID=260) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:24.348+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:41:24.350+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:24.349+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:24.364+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:24.361+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 9
    ) as dag:
    ^
SyntaxError: invalid syntax
[2023-09-05T09:41:24.365+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:24.430+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.099 seconds
[2023-09-05T09:41:28.528+0000] {processor.py:157} INFO - Started process (PID=265) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:28.529+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:41:28.531+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:28.530+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:28.550+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:28.544+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 4, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 572, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 216, in create_timetable
    return CronDataIntervalTimetable(interval, timezone)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/timetables/_cron.py", line 60, in __init__
    descriptor = ExpressionDescriptor(
  File "/home/airflow/.local/lib/python3.8/site-packages/cron_descriptor/ExpressionDescriptor.py", line 76, in __init__
    self._expression_parts = parser.parse()
  File "/home/airflow/.local/lib/python3.8/site-packages/cron_descriptor/ExpressionParser.py", line 79, in parse
    raise MissingFieldException("ExpressionDescriptor.expression")
cron_descriptor.Exception.MissingFieldException: Field 'ExpressionDescriptor.expression' not found.
[2023-09-05T09:41:28.551+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:28.597+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.083 seconds
[2023-09-05T09:41:30.552+0000] {processor.py:157} INFO - Started process (PID=270) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:30.553+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:41:30.556+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:30.555+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:30.568+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:30.566+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 4, in <module>
    with DAG(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 572, in __init__
    self.timetable = create_timetable(schedule_interval, self.timezone)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dag.py", line 216, in create_timetable
    return CronDataIntervalTimetable(interval, timezone)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/timetables/_cron.py", line 60, in __init__
    descriptor = ExpressionDescriptor(
  File "/home/airflow/.local/lib/python3.8/site-packages/cron_descriptor/ExpressionDescriptor.py", line 76, in __init__
    self._expression_parts = parser.parse()
  File "/home/airflow/.local/lib/python3.8/site-packages/cron_descriptor/ExpressionParser.py", line 84, in parse
    raise FormatException(
cron_descriptor.Exception.FormatException: Error: Expression only has 1 parts.  At least 5 part are required.
[2023-09-05T09:41:30.569+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:30.610+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.063 seconds
[2023-09-05T09:41:40.670+0000] {processor.py:157} INFO - Started process (PID=275) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:40.671+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:41:40.673+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:40.672+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:40.701+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:41:40.729+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:40.728+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:41:40.792+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:41:40.791+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:41:40.845+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.186 seconds
[2023-09-05T09:42:10.958+0000] {processor.py:157} INFO - Started process (PID=286) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:10.960+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:42:10.961+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:42:10.961+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:10.977+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:11.264+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:42:11.263+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:42:11.290+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:42:11.290+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:42:11.311+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.358 seconds
[2023-09-05T09:42:41.562+0000] {processor.py:157} INFO - Started process (PID=298) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:41.564+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:42:41.566+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:42:41.566+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:41.587+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:41.617+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:42:41.617+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:42:41.822+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:42:41.822+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:42:41.865+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.310 seconds
[2023-09-05T09:42:51.997+0000] {processor.py:157} INFO - Started process (PID=310) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:51.999+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:42:52.000+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:42:52.000+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:52.038+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:52.069+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:42:52.069+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:42:52.310+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:42:52.310+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:42:52.343+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.357 seconds
[2023-09-05T09:42:56.408+0000] {processor.py:157} INFO - Started process (PID=315) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:56.410+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:42:56.411+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:42:56.410+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:56.415+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:42:56.413+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 4
    defa
    ^
IndentationError: unexpected indent
[2023-09-05T09:42:56.415+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:56.455+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.056 seconds
[2023-09-05T09:42:58.487+0000] {processor.py:157} INFO - Started process (PID=320) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:58.490+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:42:58.494+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:42:58.492+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:58.502+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:42:58.499+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 4
    default
    ^
IndentationError: unexpected indent
[2023-09-05T09:42:58.504+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:42:58.536+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.071 seconds
[2023-09-05T09:43:04.587+0000] {processor.py:157} INFO - Started process (PID=325) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:04.589+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:43:04.590+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:04.589+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:04.599+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:04.594+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 4, in <module>
    default
NameError: name 'default' is not defined
[2023-09-05T09:43:04.600+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:04.639+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.060 seconds
[2023-09-05T09:43:11.688+0000] {processor.py:157} INFO - Started process (PID=330) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:11.690+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:43:11.692+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:11.692+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:11.702+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:11.697+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 4, in <module>
    default_args
NameError: name 'default_args' is not defined
[2023-09-05T09:43:11.703+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:11.746+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.067 seconds
[2023-09-05T09:43:12.731+0000] {processor.py:157} INFO - Started process (PID=335) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:12.732+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:43:12.734+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:12.733+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:12.743+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:12.741+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 4
    default_args =
                 ^
SyntaxError: invalid syntax
[2023-09-05T09:43:12.744+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:12.807+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.082 seconds
[2023-09-05T09:43:16.849+0000] {processor.py:157} INFO - Started process (PID=348) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:16.853+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:43:16.856+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:16.855+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:17.126+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:17.156+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:17.156+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:43:17.199+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:17.199+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:43:17.231+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.388 seconds
[2023-09-05T09:43:18.937+0000] {processor.py:157} INFO - Started process (PID=353) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:18.939+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:43:18.945+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:18.945+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:19.201+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:19.236+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:19.235+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:43:19.294+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:19.294+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:43:19.337+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.412 seconds
[2023-09-05T09:43:39.556+0000] {processor.py:157} INFO - Started process (PID=358) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:39.557+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:43:39.558+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:39.558+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:39.576+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:39.602+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:39.602+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:43:39.641+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:39.641+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:43:39.676+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.123 seconds
[2023-09-05T09:43:43.632+0000] {processor.py:157} INFO - Started process (PID=363) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:43.634+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:43:43.636+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:43.635+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:43.658+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:43.677+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:43.677+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:43:43.705+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:43.704+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:43:43.727+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.106 seconds
[2023-09-05T09:43:46.790+0000] {processor.py:157} INFO - Started process (PID=375) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:46.793+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:43:46.796+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:46.795+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:46.849+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:46.881+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:46.881+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:43:46.912+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:46.912+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:43:46.936+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.157 seconds
[2023-09-05T09:43:49.823+0000] {processor.py:157} INFO - Started process (PID=380) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:49.824+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:43:49.826+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:49.825+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:49.852+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:49.879+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:49.878+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:43:49.926+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:49.925+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:43:49.960+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.144 seconds
[2023-09-05T09:43:53.038+0000] {processor.py:157} INFO - Started process (PID=385) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:53.041+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:43:53.043+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:53.042+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:53.065+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:53.099+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:53.098+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:43:53.133+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:53.133+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:43:53.154+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.130 seconds
[2023-09-05T09:43:56.108+0000] {processor.py:157} INFO - Started process (PID=390) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:56.109+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:43:56.112+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:56.111+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:56.118+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:56.116+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 7
    }
    ^
SyntaxError: invalid syntax
[2023-09-05T09:43:56.119+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:56.149+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.054 seconds
[2023-09-05T09:43:58.208+0000] {processor.py:157} INFO - Started process (PID=395) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:58.209+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:43:58.211+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:58.210+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:58.215+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:43:58.214+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 7
    }
    ^
SyntaxError: invalid syntax
[2023-09-05T09:43:58.215+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:43:58.242+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.040 seconds
[2023-09-05T09:44:02.239+0000] {processor.py:157} INFO - Started process (PID=400) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:02.241+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:02.242+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:02.241+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:02.266+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:02.296+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:02.296+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:44:02.329+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:02.329+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:44:02.363+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.130 seconds
[2023-09-05T09:44:03.311+0000] {processor.py:157} INFO - Started process (PID=405) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:03.312+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:03.313+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:03.312+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:03.328+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:03.353+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:03.352+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:44:03.385+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:03.385+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:44:03.410+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.105 seconds
[2023-09-05T09:44:07.442+0000] {processor.py:157} INFO - Started process (PID=410) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:07.443+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:07.444+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:07.444+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:07.449+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:07.448+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 8
    }
    ^
SyntaxError: invalid syntax
[2023-09-05T09:44:07.450+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:07.483+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.047 seconds
[2023-09-05T09:44:10.499+0000] {processor.py:157} INFO - Started process (PID=415) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:10.500+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:10.502+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:10.501+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:10.506+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:10.504+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 8
    }
    ^
SyntaxError: invalid syntax
[2023-09-05T09:44:10.506+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:10.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.039 seconds
[2023-09-05T09:44:11.541+0000] {processor.py:157} INFO - Started process (PID=420) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:11.542+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:11.544+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:11.543+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:11.549+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:11.547+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 8
    }
    ^
SyntaxError: invalid syntax
[2023-09-05T09:44:11.549+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:11.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.040 seconds
[2023-09-05T09:44:13.580+0000] {processor.py:157} INFO - Started process (PID=425) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:13.581+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:13.582+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:13.582+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:13.587+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:13.585+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 8
    }
    ^
SyntaxError: invalid syntax
[2023-09-05T09:44:13.588+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:13.614+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.039 seconds
[2023-09-05T09:44:15.635+0000] {processor.py:157} INFO - Started process (PID=437) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:15.636+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:15.638+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:15.637+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:15.644+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:15.642+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 8
    }
    ^
SyntaxError: invalid syntax
[2023-09-05T09:44:15.645+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:15.668+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.040 seconds
[2023-09-05T09:44:17.676+0000] {processor.py:157} INFO - Started process (PID=442) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:17.677+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:17.679+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:17.678+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:17.704+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:17.740+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:17.739+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:44:17.790+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:17.790+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:44:17.823+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.153 seconds
[2023-09-05T09:44:28.833+0000] {processor.py:157} INFO - Started process (PID=447) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:28.836+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:28.838+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:28.837+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:28.867+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:28.902+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:28.901+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:44:28.964+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:28.963+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:44:29.002+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.186 seconds
[2023-09-05T09:44:39.033+0000] {processor.py:157} INFO - Started process (PID=452) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:39.036+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:39.039+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:39.038+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:39.081+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:39.124+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:39.124+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:44:39.180+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:39.180+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:44:39.242+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.219 seconds
[2023-09-05T09:44:53.188+0000] {processor.py:157} INFO - Started process (PID=463) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:53.189+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:53.190+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:53.190+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:53.204+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:53.223+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:53.222+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:44:53.249+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:53.249+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:44:53.274+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.090 seconds
[2023-09-05T09:44:55.347+0000] {processor.py:157} INFO - Started process (PID=468) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:55.349+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:55.356+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:55.354+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:55.369+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:55.365+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 7, in <module>
    'retry_delay':timedelta(min)
TypeError: unsupported type for timedelta days component: builtin_function_or_method
[2023-09-05T09:44:55.370+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:55.439+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.108 seconds
[2023-09-05T09:44:57.362+0000] {processor.py:157} INFO - Started process (PID=473) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:57.363+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:57.364+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:57.364+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:57.368+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:57.366+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 7
    'retry_delay':timedelta(minutes=)
                                    ^
SyntaxError: invalid syntax
[2023-09-05T09:44:57.368+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:57.388+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.032 seconds
[2023-09-05T09:44:59.408+0000] {processor.py:157} INFO - Started process (PID=478) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:59.411+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:44:59.416+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:59.415+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:59.474+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:44:59.509+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:59.508+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:44:59.545+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:44:59.545+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:44:59.576+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.181 seconds
[2023-09-05T09:45:06.500+0000] {processor.py:157} INFO - Started process (PID=483) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:06.501+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:45:06.502+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:06.502+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:06.506+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:06.504+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 13
    description='this is my first dag that we write',
    ^
SyntaxError: invalid syntax
[2023-09-05T09:45:06.506+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:06.531+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.036 seconds
[2023-09-05T09:45:07.524+0000] {processor.py:157} INFO - Started process (PID=488) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:07.525+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:45:07.526+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:07.526+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:07.532+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:07.529+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 13
    description='this is my first dag that we write',
               ^
SyntaxError: invalid syntax
[2023-09-05T09:45:07.533+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:07.590+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.081 seconds
[2023-09-05T09:45:16.671+0000] {processor.py:157} INFO - Started process (PID=499) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:16.674+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:45:16.677+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:16.676+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:16.685+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:16.682+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 12
    default_args=def
                 ^
SyntaxError: invalid syntax
[2023-09-05T09:45:16.687+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:16.726+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.067 seconds
[2023-09-05T09:45:19.726+0000] {processor.py:157} INFO - Started process (PID=504) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:19.727+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:45:19.728+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:19.727+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:19.733+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:19.730+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 13
    description='this is my first dag that we write',
    ^
SyntaxError: invalid syntax
[2023-09-05T09:45:19.734+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:19.792+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.073 seconds
[2023-09-05T09:45:22.853+0000] {processor.py:157} INFO - Started process (PID=509) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:22.854+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:45:22.857+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:22.856+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:22.888+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:23.183+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:23.183+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:45:23.238+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:23.237+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:45:23.293+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.456 seconds
[2023-09-05T09:45:28.957+0000] {processor.py:157} INFO - Started process (PID=514) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:28.959+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:45:28.962+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:28.961+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:28.993+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:29.020+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:29.020+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:45:29.084+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:29.084+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:45:29.119+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.171 seconds
[2023-09-05T09:45:41.042+0000] {processor.py:157} INFO - Started process (PID=519) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:41.043+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:45:41.044+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:41.043+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:41.050+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:41.047+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 3
    from airflow
               ^
SyntaxError: invalid syntax
[2023-09-05T09:45:41.051+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:41.094+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.059 seconds
[2023-09-05T09:45:44.088+0000] {processor.py:157} INFO - Started process (PID=524) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:44.091+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:45:44.093+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:44.092+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:44.098+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:44.097+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 3
    from airflow.operators
                         ^
SyntaxError: invalid syntax
[2023-09-05T09:45:44.098+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:44.138+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.059 seconds
[2023-09-05T09:45:46.205+0000] {processor.py:157} INFO - Started process (PID=536) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:46.206+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:45:46.208+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:46.208+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:46.214+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:46.212+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 3
    from airflow.operators.bash
                              ^
SyntaxError: invalid syntax
[2023-09-05T09:45:46.215+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:46.298+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.110 seconds
[2023-09-05T09:45:49.227+0000] {processor.py:157} INFO - Started process (PID=541) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:49.228+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:45:49.230+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:49.229+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:49.233+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:49.232+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 3
    from airflow.operators.bash import
                                     ^
SyntaxError: invalid syntax
[2023-09-05T09:45:49.240+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:49.273+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.052 seconds
[2023-09-05T09:45:52.306+0000] {processor.py:157} INFO - Started process (PID=546) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:52.307+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:45:52.310+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:52.309+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:52.332+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:45:52.351+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:52.351+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:45:52.399+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:45:52.399+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:45:52.441+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.142 seconds
[2023-09-05T09:46:01.537+0000] {processor.py:157} INFO - Started process (PID=551) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:01.538+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:01.540+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:01.539+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:01.555+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:01.553+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 18, in <module>
    tas
NameError: name 'tas' is not defined
[2023-09-05T09:46:01.555+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:01.589+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.056 seconds
[2023-09-05T09:46:05.572+0000] {processor.py:157} INFO - Started process (PID=556) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:05.573+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:05.574+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:05.573+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:05.579+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:05.577+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 18
    task1 =
           ^
SyntaxError: invalid syntax
[2023-09-05T09:46:05.580+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:05.622+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.058 seconds
[2023-09-05T09:46:08.589+0000] {processor.py:157} INFO - Started process (PID=561) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:08.590+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:08.591+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:08.590+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:08.607+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:08.605+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 18, in <module>
    task1 = Ba
NameError: name 'Ba' is not defined
[2023-09-05T09:46:08.608+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:08.651+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.067 seconds
[2023-09-05T09:46:10.701+0000] {processor.py:157} INFO - Started process (PID=566) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:10.702+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:10.704+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:10.703+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:10.720+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:10.719+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 18, in <module>
    task1 = Bash
NameError: name 'Bash' is not defined
[2023-09-05T09:46:10.721+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:10.762+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.070 seconds
[2023-09-05T09:46:11.768+0000] {processor.py:157} INFO - Started process (PID=571) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:11.769+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:11.771+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:11.770+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:11.797+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:11.828+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:11.826+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:46:11.870+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:11.870+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:46:11.909+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.152 seconds
[2023-09-05T09:46:13.834+0000] {processor.py:157} INFO - Started process (PID=576) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:13.835+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:13.839+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:13.838+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:13.855+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:13.851+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 18, in <module>
    task1 = BashOperator()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 419, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-09-05T09:46:13.857+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:13.890+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.062 seconds
[2023-09-05T09:46:15.884+0000] {processor.py:157} INFO - Started process (PID=581) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:15.886+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:15.887+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:15.887+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:15.904+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:15.902+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 18, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 419, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-09-05T09:46:15.905+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:15.953+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.083 seconds
[2023-09-05T09:46:34.091+0000] {processor.py:157} INFO - Started process (PID=593) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:34.093+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:34.094+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:34.094+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:34.104+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:34.103+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    task
NameError: name 'task' is not defined
[2023-09-05T09:46:34.104+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:34.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.039 seconds
[2023-09-05T09:46:35.129+0000] {processor.py:157} INFO - Started process (PID=598) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:35.130+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:35.132+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:35.131+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:35.142+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:35.141+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    task_
NameError: name 'task_' is not defined
[2023-09-05T09:46:35.143+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:35.163+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.042 seconds
[2023-09-05T09:46:38.204+0000] {processor.py:157} INFO - Started process (PID=603) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:38.205+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:38.207+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:38.206+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:38.216+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:38.215+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 19, in <module>
    task_id
NameError: name 'task_id' is not defined
[2023-09-05T09:46:38.217+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:38.236+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.041 seconds
[2023-09-05T09:46:41.255+0000] {processor.py:157} INFO - Started process (PID=608) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:41.256+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:41.257+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:41.257+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:41.271+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:41.269+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 18, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 419, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-09-05T09:46:41.271+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:41.293+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.044 seconds
[2023-09-05T09:46:45.348+0000] {processor.py:157} INFO - Started process (PID=613) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:45.350+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:45.354+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:45.353+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:45.381+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:45.378+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 18, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 419, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-09-05T09:46:45.382+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:45.408+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.071 seconds
[2023-09-05T09:46:49.422+0000] {processor.py:157} INFO - Started process (PID=625) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:49.424+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:49.426+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:49.425+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:49.439+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:49.438+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 18, in <module>
    task1 = BashOperator(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 419, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'bash_command'
[2023-09-05T09:46:49.440+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:49.462+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.049 seconds
[2023-09-05T09:46:52.490+0000] {processor.py:157} INFO - Started process (PID=630) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:52.491+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:52.492+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:52.492+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:52.496+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:52.495+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 21
    )
    ^
SyntaxError: invalid syntax
[2023-09-05T09:46:52.496+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:52.521+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.036 seconds
[2023-09-05T09:46:55.530+0000] {processor.py:157} INFO - Started process (PID=635) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:55.530+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:46:55.531+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:55.531+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:55.551+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:46:55.780+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:55.780+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:46:55.826+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:46:55.826+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:46:55.863+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.341 seconds
[2023-09-05T09:47:05.644+0000] {processor.py:157} INFO - Started process (PID=640) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:47:05.645+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:47:05.646+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:47:05.646+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:47:05.668+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:47:05.681+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:47:05.681+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:47:05.715+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:47:05.715+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:47:05.748+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.112 seconds
[2023-09-05T09:47:25.838+0000] {processor.py:157} INFO - Started process (PID=652) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:47:25.842+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:47:25.846+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:47:25.845+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:47:25.882+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:47:25.877+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/my_first_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_first_dag.py", line 23, in <module>
    tas
NameError: name 'tas' is not defined
[2023-09-05T09:47:25.884+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:47:25.922+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.099 seconds
[2023-09-05T09:47:26.921+0000] {processor.py:157} INFO - Started process (PID=657) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:47:26.922+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:47:26.924+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:47:26.923+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:47:26.946+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:47:27.196+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:47:27.196+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:47:27.249+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:47:27.249+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:47:27.305+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.391 seconds
[2023-09-05T09:47:57.569+0000] {processor.py:157} INFO - Started process (PID=669) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:47:57.571+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:47:57.572+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:47:57.572+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:47:57.589+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:47:57.625+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:47:57.625+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:47:57.659+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:47:57.659+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-08-30T00:00:00+00:00, run_after=2023-08-31T00:00:00+00:00
[2023-09-05T09:47:57.687+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.123 seconds
[2023-09-05T09:48:27.870+0000] {processor.py:157} INFO - Started process (PID=702) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:48:27.872+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:48:27.873+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:48:27.873+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:48:27.886+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:48:27.916+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:48:27.916+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:48:27.944+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:48:27.944+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T09:48:27.965+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.099 seconds
[2023-09-05T09:48:58.183+0000] {processor.py:157} INFO - Started process (PID=714) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:48:58.183+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:48:58.184+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:48:58.184+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:48:58.204+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:48:58.260+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:48:58.260+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:48:58.313+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:48:58.312+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T09:48:58.347+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.169 seconds
[2023-09-05T09:49:28.551+0000] {processor.py:157} INFO - Started process (PID=726) to work on /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:49:28.556+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/my_first_dag.py for tasks to queue
[2023-09-05T09:49:28.559+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:49:28.557+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:49:28.605+0000] {processor.py:839} INFO - DAG(s) dict_keys(['my_first_dag']) retrieved from /opt/airflow/dags/my_first_dag.py
[2023-09-05T09:49:28.656+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:49:28.656+0000] {dag.py:2907} INFO - Sync 1 DAGs
[2023-09-05T09:49:28.707+0000] {logging_mixin.py:151} INFO - [2023-09-05T09:49:28.707+0000] {dag.py:3677} INFO - Setting next_dagrun for my_first_dag to 2023-09-05T00:00:00+00:00, run_after=2023-09-06T00:00:00+00:00
[2023-09-05T09:49:28.743+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/my_first_dag.py took 0.204 seconds
